### ISSUE TITLE
همه ادرس ها

### ISSUE THREAD

**Issue by prxpostern** [bepass-org/smartSNI#10]
سلام . این خیلی سخت یا نا ممکنه که بشه فهمید مثلا فلان بازی روی اندورید داره از چه دامنه هایی استفاده میکنه که اونها رو تو کانفیگ وارد کنیم !!! این شاید ناممکن باشه . اگر راهی باشه که ترافیک همه دامنه ها رو به ای پی تبدیل کنه خیلی بهتر ازینه که فقط چند تا دامنه رو بخواهیم دستی بزنیم.  اگر راهی داره لطفا راهنمایی فرمایید . ممنون

**Comment by AkramiPro** [comment]
به جای دامنه دات خالی بزن تا همه دامنه ها منتقل کنه . توی صفحه اصلی هم توضیح داده شده

**Comment by prxpostern** [comment]
چه خوب

خیلی ممنون
