### ISSUE TITLE
راهنمایی بابت باز کردن سرویس های خاص

### ISSUE THREAD

**Issue by ahmadta72** [bepass-org/smartSNI#16]
با سلام و احترام؛ ضمن تشکر و خسته نباشید. من از اسکریپت استفاده کردم و تونستم بخش زیادی از سرویس هارو باز کنم. 
سوالی که داشتم در ارتباط با سرویس هایی بود که متفاوت مارو تحریم کردند. 2 نمونه مثال می زنم. 
مثلا chatgpt یا سرویس های گوگل (مثل گوگل ارت)
ممنون میشم راهنمایی کنید که سرویس های dns ایرانی به چه صورتی این سرویس هارو باز می کنند و با چه راه حلی می تونیم از سرویس شما برای بازگشایی این نوع سرویس ها بهره ببریم. با تشکر از شما

**Comment by mehdiabr** [comment]
مگر تو گوگل ارت یا chgpt با این سرویس چه مشکلی دارید؟

**Comment by ahmadta72** [comment]
> مگر تو گوگل ارت یا chgpt با این سرویس چه مشکلی دارید؟

سرویس های گوگل خطای 403. That’s an error. می دهند و سرویس openai در بخش chatgpt » Unable to load site که من هر دو سرویس را به عنوان نمونه لینک هاشون رو برای شما هم ضمیمه می کنم. 

https://earth.google.com/web/
https://chat.openai.com/

`من فایل config.json را به صورت proxy all domains قرار دادم.`
با تشکر

**Comment by mehdiabr** [comment]
خب بایدم اینطور باشه! ایپی شما برا ایران!! فایل کانفیگ یا درست ست نکردی یا اتصالت ب سرویس مشکلی داشته

**Comment by ahmadta72** [comment]
> خب بایدم اینطور باشه! ایپی شما برا ایران!! فایل کانفیگ یا درست ست نکردی یا اتصالت ب سرویس مشکلی داشته

```
{
  "host": "mydomain.com",
  "domains": {
    ".": "my ip"
  }
}
```

فایل config.json را به صورت proxy all domains قرار دادم. 
الان طبق صحبت شما آی پی که ایران هست اما فایل کانفیگ روی خیلی از سرویس ها داره جواب میده! (اتصال به یک DNS-over-HTTPS روی مرورگر ها هم فکر نمی کنم موردی خاصی باشه که اتصال دچار مشکل باشه. 

الان برای شما : 
```
https://earth.google.com/web/
https://chat.openai.com/ 
```
این 2 مورد باز میشه با آی پی ایران؟

**Comment by mehdiabr** [comment]
با این سرویس، سایت گوگل مپ اوکیه مشکلی نداره، درمورد chatgpt هم اون سایت ب ایپی حساس، برو ب این سایت proxycheck.io ببین ایا ایپی ت بعنوان یک پروکسی شناخته شده هست یانه.اگر اینطور بود، با یه ایپی تمییز مشکلت حل میشه.

**Comment by ahmadta72** [comment]
فکر می کنم شما گوگل مپ رو با گوگل ارث اشتباه گرفتید.  آی پی من هم تمیز هست اما در مجوع هیچ کدام از سرویس های تحریم شده گوگل کار نمی کنه. احتمالا با توجه به گره خوردن این بخش از سرویس های گوگل و..  دولوپر های این پروژه که دمشون گرم از همین جا خسته نباشید بهشون میگم.. چون سواد خوبی در این بخش داره احتمالا بتونه کمک کنه که تا به امروز پیامی از contributors های اصلی پروژه در این issue درج نشده است.

**Comment by ahmadta72** [comment]
سلام مشکل حل شد. مرسی از توسعه دهندگان عزیز
