### ISSUE TITLE
عدم کارکرد

### ISSUE THREAD

**Issue by Alireza78na** [bepass-org/smartSNI#3]
سلام و خسته نباشید.
من از طریق اسکریپت نصب اتوماتیک ، Smart SNI رو نصب کردم ( قبلا دستی نصب کردم ولی نتونستم استفاده کنم درحالی که همه چی اوکی بود )
اما بعد از طی همه ی مراحل ، بازم نتونستم ازش استفاده کنم

دامین چک شده فیلتر نیست
آیپی آزاده و فیلتر نیست
سرور از هتزنره

تست روی DoT برای اندرویده و ارور Couldn't Connect میده.
روی سرور هم کلا فایروال فعال نیست و همه ی پورتا به صورت پیش فرض بازن.

ممکنه خود هتزنر پورتایی که DNS لازم داره رو بسته باشه؟
یا اینکه اگه نکته ای داره نصبش لطفا بگید.
مثلا چه پورتایی استفاده میشه و حتما باید باز باشه و ..... 

ممنونم

**Comment by uoosef** [comment]
سلام DOT بخاطر تغییراتی که برای بهبود مدیریت رم داده بودیم یه باگی داشت که فیکس شد، لطفا دوباره نصب کنید و امتحان کنید

**Comment by SadeghPM** [comment]
همچنان مشکل هست و کار نمیکنه
با installer نصب کردم.

**Comment by SadeghPM** [comment]
برای تست همچین چیزی باید جواب بده:
`dnslookup www.example.com https://xxxx.com/dns-query
`
اما خطا برمیگردونه:
```
dnslookup v. 1.8.1-8619
2023/11/24 06:56:34 [fatal] Cannot make the DNS request: expected status 200, got 500 from https://xxxx.com
```

**Comment by AkramiPro** [comment]
من چون دیدم چند نفر میگن کار نمیکنه خودم رفتم تست کردم و دیدم مشکل داره 
برای اینکه مطمئن بشم مشکل از فیلترنت نیست کلا با 2 تا سرور خارج تست کردم
فکر کنم یه مشکلی داره . چون همه چیز ظاهرا اوکی هست . هم nginx ران هست و هم پورت های 443 8443 80 853 آپ هستن و دارن لیستن میکنن

![image](https://github.com/bepass-org/smartSNI/assets/54323929/8287a481-7e16-4781-92a8-a1ede805520c)
----------------
![image](https://github.com/bepass-org/smartSNI/assets/54323929/5b1fae9a-511c-448f-8c20-efd6a0960302)
----------------
![image](https://github.com/bepass-org/smartSNI/assets/54323929/af27d01a-1133-4ff4-a1b7-364d609564ab)
> صرفا برای اینکه بدونم up هست یا نه توی مرورگر زدم

**Comment by uoosef** [comment]
دوستان من کد رو بازبینی کردم، یه ایرادی بود توی doh که فقط post هندل میشد و get هندل نمیشد که رفع شد،
برای تست لطفا از ابزار q استفاده کنید.
https://github.com/natesales/q
تو تصویر زیر هم میبیند که هم dot هم doh دارن جواب میدن
![dotdoh](https://github.com/bepass-org/smartSNI/assets/43346478/583820a2-2efe-4422-b9a3-0fb5b34fba80)
فقط در خصوص private dns اندروید اونطور که من تست کردم انگار روی ایرانسل بستن پورت 853 رو و کار نمیکنه ولی روی همراه اول تست کردم و درسته

**Comment by uoosef** [comment]
برای بروزرسانی یا مجددا نصب کنید یا اینکه سرویس رو خاموش کنید و پوشه برنامه رو مجددا clone کنید و بعد با
go run main.go
تست بگیرید که درست اجرا بشه، بعد میتونید سرویس رو مجددا راه اندازی کنید

**Comment by Alireza78na** [comment]
ممنون بابت زحماتتون

من نسخه ی جدید رو هم نصب کردم رو سرور جدید ، ولی هنوزم موفق نشدم با گوشی متصل شم و همون ارور قبل رو میگیرم روی DoT
البته با DoT شکن میتونم وصل شم ( برای اینکه تست کنم مشکل از گوشی و اینترنت و ... نباشه )

DoH رو تست نکردم

**Comment by SadeghPM** [comment]
همچنان جواب نمیده
مشکلی که در کدها دیده میشه اینه که حالت های مختلف dns-query هندل نمیشه. مثلا برای حالت زیر :
`‍‍GET /dns-query?dns=AAABAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ`

من  با لاگ nginx میبینم که ابزارهای مختلف چطور dns-query میدن و کد go چطور هندل میکنه این حالت هارو.

**Comment by AkramiPro** [comment]
من حذف کردم و از اول نصب کردم توسط اسکریپت همچنان همون خطای قبلی رو میده 
من فکر کنم خروجی استاندارد رو نداره و همه حالت هایی که برنامه ها بهش کوئری میزنن رو ساپورت نمیکنه
من داخل فایرفاکس بخش doh رفتم و وارد کردم و خطا میده 

![image](https://github.com/bepass-org/smartSNI/assets/54323929/96d8a873-f687-43af-9018-748c1b351957)

![image](https://github.com/bepass-org/smartSNI/assets/54323929/05b2fa8e-f4b2-4e2b-844a-be23b74a6348)

**Comment by AkramiPro** [comment]
اینم اضافه کنم که من با یک برنامه که مخصوص تست dns هست تست کردم و ظاهرا در یک حالت خاص داره کار میکنه 
ولی فکر کنم برنامه های دیگه مثل مرورگر ها دارن یه روش دیگه ای درخواست میدن که کار نمیده اون 

![image](https://github.com/bepass-org/smartSNI/assets/54323929/5e254a9d-8c49-4835-88f2-0f6b65b4bd69)

**Comment by uoosef** [comment]
دوستان من خودم مستقیما تو کروم و فایرفاکس وارد نمیکردم ولی شما چون گزارش دادید تست کردم و تو فایرفاکس مشکلی نداشت ولی کروم خیلی سختگیره و من تنظیمات nginx و همچنین جواب ساختگی که از طرف ابزار برمیگرده رو دستکاری کردم که رو کروم هم کار بکنه
![chrome](https://github.com/bepass-org/smartSNI/assets/43346478/b6b353e6-f229-400d-8218-841300e6debf)
![ffox](https://github.com/bepass-org/smartSNI/assets/43346478/5a056156-2ebd-483e-94a4-385119f9ec48)
نسخه جدید رو لطفا تست کنید
ضمنا دوستان لطفا حتما بگید که روی چه اینترنت، نرم‌افزار و سیستم‌عاملی به مشکل خوردید و اینکه چطور نصب کردید که بتونم سریعتر مشکلات رو حل کنم

**Comment by uoosef** [comment]
@AkramiPro اون خطای فایرفاکس یعنی کلا نتونسته به doh وصل بشه یبار با فیلترشکن روشن امتحان کنید اگر باز این خطا رو گرفتید احتمالا فرایند این نصب مشکل داره اگر نه احتمالا دامنه یا ایپی فیلتره، در غیر اینصورت یبار بصورت دستی نصب کنید شاید اسکرپت نصب خودکار مشکل داره

**Comment by uoosef** [comment]
@SadeghPM من این url ای که گذاشتید رو تست کردم جواب میده، شما فراند نصب و تستتون به چه صورتی بوده ؟
![ggl](https://github.com/bepass-org/smartSNI/assets/43346478/b5f5e3f3-f6a9-4bfe-a27c-842c8ddee0ea)

**Comment by uoosef** [comment]
الان بنظر میاد داره تو تمام حالتها درست کار میکنه اگر به مشکل خوردید فرایند نصب رو دستی یبار انجام بدید شاید اسکریپت نصب ایرادی داره

**Comment by SadeghPM** [comment]
> @SadeghPM من این url ای که گذاشتید رو تست کردم جواب میده، شما فراند نصب و تستتون به چه صورتی بوده ؟ ![ggl](https://user-images.githubusercontent.com/43346478/285514383-b5f5e3f3-f6a9-4bfe-a27c-842c8ddee0ea.png)

من با installer نصب میکنم
تست رو `dnslookup www.example.com https://xxxx.com/dns-query`

**Comment by SadeghPM** [comment]
نصب دستی هم آخرش این خطا رو داره:
```
root@ip-13-46:~/smartSNI# ./smartSNI 
2023/11/24 17:24:21 Starting SSNI proxy server on :443, :853...
2023/11/24 17:24:21 listen tcp :443: bind: address already in use

```

**Comment by AkramiPro** [comment]
> نصب دستی هم آخرش این خطا رو داره:
> 
> ```
> root@ip-13-46:~/smartSNI# ./smartSNI 
> 2023/11/24 17:24:21 Starting SSNI proxy server on :443, :853...
> 2023/11/24 17:24:21 listen tcp :443: bind: address already in use
> ```

این خطاش به خاطر این هست که نسخه قبلی رو حذف نکردید کامل و پورت 443 داره استفاده میشه هنوز 
همون اسکریپت رو دوبار اجرا کنید فقط این دفعه گزینه uninstall رو بزنید که حذف کنه کامل

**Comment by SadeghPM** [comment]
کامل حذف میکنم. با اسکریپت uninstall میزنم و دستی هم سرویسش رو چک میکنم ران نباشه.

**Comment by uoosef** [comment]
برای اینکه چک کنید چه پروسه ای داره به پورت 443 گوش میده میتونید بزنید
lsof -i :443
بعد اون پروسه رو با idش کیل کنید& البته من توصیه میکنم که کلا بزنید از اول سیستم عامل نصب بشه و تر و تمیز بیاد بالا

**Comment by uoosef** [comment]
هرکدوم از دوستان اگر بازم مشکل داشتید یه سابدامنه که پشت cdn نباشه رو ست کنید رو سرورتون و تو تلگرام برای من ssh بفرستید که چک کنم
@uoosuoos

**Comment by AkramiPro** [comment]
مهندس جان من مشکل رو فهمیدم. این اسکریپت نصب بخش Uninstall مشکل داره و تا الان سر کار بودیم همه
شما این همه زحمت میکشیدی اپدیت میدادی ولی من هر دفعه Uninstall که میکردم این nginx و main.go رو stop نمیکرده برای همین نسخه جدید اعمال نمیشده
الان اوکی شد و به درستی کار میکنه
فقط بعضی سایت ها مشکل دارن . مثلا من موقع نصب دامنه رو دات قرار دادم که از همه سایت ها پشتیبانی کنه
الان google.com که میزنم 403 میده 
ولی سایت های دیگه رو داره به درستی باز میکنه . مثلا سایت ip-api.com که چک میکنم به درستی داره ایپی سرور خارج رو میزنه

![image](https://github.com/bepass-org/smartSNI/assets/54323929/391ced0c-49ee-4c2d-b00d-dce3238e17b2)

![image](https://github.com/bepass-org/smartSNI/assets/54323929/819bbe08-ca26-4394-9d84-e0bbbbb10d4a)

**Comment by uoosef** [comment]
مخلصم مهندس، فک کنم ایئی سروتون کثیفه که گوگل گیر میده احتمالا روش فیلترشکن بوده یه ایئی دیگه برای سرورتون تست کنید نتیجه رو به من بگید

**Comment by AkramiPro** [comment]
نه تازه نصب کردم برای تست این اسکریپت . هتزنر هست . احتمالا ایپیش چرخیده دست من رسیده کثیفش کردن
الان روش warp میزنم تست میکنم

**Comment by uoosef** [comment]
دوستان کسی میتونه رو ایرانسل و مخابرات این نسخه اخر اخرو تست کنه ؟ هم dot هم doh

**Comment by AkramiPro** [comment]
> دوستان کسی میتونه رو ایرانسل و مخابرات این نسخه اخر اخرو تست کنه ؟ هم dot هم doh

من ایرانسل تست کردم dot کار نمیده ولی doh اوکی هست

**Comment by uoosef** [comment]
> > دوستان کسی میتونه رو ایرانسل و مخابرات این نسخه اخر اخرو تست کنه ؟ هم dot هم doh
> 
> من ایرانسل تست کردم dot کار نمیده ولی doh اوکی هست

رو همراه اول dot کار میکنه ؟

**Comment by AkramiPro** [comment]
> مخلصم مهندس، فک کنم ایئی سروتون کثیفه که گوگل گیر میده احتمالا روش فیلترشکن بوده یه ایئی دیگه برای سرورتون تست کنید نتیجه رو به من بگید

من الان warp هم زدم روی سرور و ip-api.com هم تست کردم ایپی تغییر کرد ولی این google.com لامصب کماکان 403 میده
مشکل از ssl نیست ؟ این فکر کنم متوجه میشه یه طوری که سرور واسط هست شاید میخواید از MITM جلوگیری کنه اینطوری میشه

**Comment by uoosef** [comment]
بجای . بزنید google بعد تو فایرفاکس تست کنید ببینید بازم 403 میده یا نه اگه نده تو فایرفاکس احتمالا hsts preloaded کروم هست

**Comment by uoosef** [comment]
من الان تست کردم خودم ردیفه و قشنگ داره ایپی سرورمم بجای ایئی خودم نشون میده شاید از شانس بد شما ایپی وارپ هم کثیفه، سرور من امازون ترکیس
![image](https://github.com/bepass-org/smartSNI/assets/43346478/9f85bb07-10f2-4a38-b034-c1cef0c6f2c6)

**Comment by AkramiPro** [comment]
> > > دوستان کسی میتونه رو ایرانسل و مخابرات این نسخه اخر اخرو تست کنه ؟ هم dot هم doh
> > 
> > 
> > من ایرانسل تست کردم dot کار نمیده ولی doh اوکی هست
> 
> رو همراه اول dot کار میکنه ؟

همراه فکر کنم کلا هتزنر رو فیلتر کرده بالا نمیاد . نه doh و نه dot

**Comment by uoosef** [comment]
> > > > دوستان کسی میتونه رو ایرانسل و مخابرات این نسخه اخر اخرو تست کنه ؟ هم dot هم doh
> > > 
> > > 
> > > من ایرانسل تست کردم dot کار نمیده ولی doh اوکی هست
> > 
> > 
> > رو همراه اول dot کار میکنه ؟
> 
> همراه فکر کنم کلا هتزنر رو فیلتر کرده بالا نمیاد . نه doh و نه dot

برای من dot میاد، ممکنه دامینتو زده باشن رو همراه اول

**Comment by Alireza78na** [comment]
> مهندس جان من مشکل رو فهمیدم. این اسکریپت نصب بخش Uninstall مشکل داره و تا الان سر کار بودیم همه شما این همه زحمت میکشیدی اپدیت میدادی ولی من هر دفعه Uninstall که میکردم این nginx و main.go رو stop نمیکرده برای همین نسخه جدید اعمال نمیشده الان اوکی شد و به درستی کار میکنه فقط بعضی سایت ها مشکل دارن . مثلا من موقع نصب دامنه رو دات قرار دادم که از همه سایت ها پشتیبانی کنه الان google.com که میزنم 403 میده ولی سایت های دیگه رو داره به درستی باز میکنه . مثلا سایت ip-api.com که چک میکنم به درستی داره ایپی سرور خارج رو میزنه
> 
> ![image](https://user-images.githubusercontent.com/54323929/285520401-391ced0c-49ee-4c2d-b00d-dce3238e17b2.png)
> 
> ![image](https://user-images.githubusercontent.com/54323929/285520712-819bbe08-ca26-4394-9d84-e0bbbbb10d4a.png)

این مشکل بخاطر فعال بودن IPv6 روی سرورای هتزنر اتفاق میوفته
منم همین مشکلو داشتم ، IPv6 رو حذف کردم اوکی شد.


ممنون از @uoosef , @AkramiPro و بقیه که کمک کردن این مشکل حل شه

**Comment by AkramiPro** [comment]
> > مهندس جان من مشکل رو فهمیدم. این اسکریپت نصب بخش Uninstall مشکل داره و تا الان سر کار بودیم همه شما این همه زحمت میکشیدی اپدیت میدادی ولی من هر دفعه Uninstall که میکردم این nginx و main.go رو stop نمیکرده برای همین نسخه جدید اعمال نمیشده الان اوکی شد و به درستی کار میکنه فقط بعضی سایت ها مشکل دارن . مثلا من موقع نصب دامنه رو دات قرار دادم که از همه سایت ها پشتیبانی کنه الان google.com که میزنم 403 میده ولی سایت های دیگه رو داره به درستی باز میکنه . مثلا سایت ip-api.com که چک میکنم به درستی داره ایپی سرور خارج رو میزنه
> > ![image](https://user-images.githubusercontent.com/54323929/285520401-391ced0c-49ee-4c2d-b00d-dce3238e17b2.png)
> > ![image](https://user-images.githubusercontent.com/54323929/285520712-819bbe08-ca26-4394-9d84-e0bbbbb10d4a.png)
> 
> این مشکل بخاطر فعال بودن IPv6 روی سرورای هتزنر اتفاق میوفته منم همین مشکلو داشتم ، IPv6 رو حذف کردم اوکی شد.
> 
> ممنون از @uoosef , @AkramiPro و بقیه که کمک کردن این مشکل حل شه

درسته یادم نبود ipv6 فعال کردم . ممنون درست شد
با تشکر از زحمات همه به خصوص مهندس عزیز @uoosef

**Comment by Nima786** [comment]
سلام دوستان، لطفاً راهنمایی کنید ، فرض کنید کن با اسکریپت بدون مشکل دامنه sub.mydomain.tld رو ست کردم. 
۱) الان چطور روی کلاینت‌های مختلف باید ست بشه این سرور؟
روی یک سرور دیگه؟ برای nameserver باید ساب دامین رو بزارم یا IP سرور رو؟
۲) توی فیلترشکن ها چطور؟ مثلا توی v2rayng همون IP رو بزاریم قسمت dns تنظیمات ؟
۳) برای پرایوت dns اندروید چی؟ اینو فقط بزارم sub.mydomain یا بصورت دیگه ای باید گذاشت ؟

**Comment by uoosef** [comment]
مخلصم دوستان خوشحالم که مشکلاتتون برطرف شد، issue رو میبندم باز مشکلی بود یه issue جدید باز کنید
