### ISSUE TITLE
support ECH 

### ISSUE THREAD

**Issue by AkramiPro** [bepass-org/smartSNI#4]
سلام بر مهندس یوسف عزیز
آقا نمیشه ی کاری کرد که ECH رو توی مروگر فعال کنیم و با استفاده از این doh درخواست ها هندل بشن ؟
چون sni که انکریپت بشه دیگه فیلتر sni بی معنی میشه از طرفی ایپی هم که تغییر دادیم باید بدون مشکل باز کنه همه چی رو و دیگه نیازی به vpn هم نداشته باشیم

**Comment by uoosef** [comment]
سلام
اینکار بدون باز کردن ترافیک ssl و tls ممکن نیست برای اینکار باید کاربر یه root certificate رو سیستمش نصب کنه که نمیدونم کار درستیه اصلا یا نه
